name: First time making ci cd pipleine

on: 
  push:
    branches:
      - main

jobs: 
  deploy:  
    runs-on:ubuntu-latest
    
    steps:
      -name: Checkout Code
       uses: actions/checkout@v4

      -name: Login using ssh
       uses:appleboy/ssh-action@v1.0.3
       with:
        host    : 210.79.128.213
        username: ubuntu
        key     : ${{ secrets.PRIVATE_KEY }}

      -name: Deploy to Excloud Server
       run : |
        cd /home/ubuntu/devops-01
        npm install
        pnpm restart 0 
    